#!/usr/bin/env bash
vpp_echo=../vpp/build-root/install-vpp_debug-native/vpp/bin/vpp_echo

## use app socket api
gdb -q --args $vpp_echo client log=100 socket-name /run/vpp/app_ns_sockets/2 uri http://10.10.10.1/12344 use-app-socket-api

## use vpp api
#gdb --args $vpp_echo client log=100 socket-name /run/vpp/app_ns_sockets/2 use-app-socket-api uri tcp://10.10.10.1/12344

#$vpp_echo client log=100 use-app-socket-api socket-name /run/vpp/app_ns_sockets/2 uri udp://10.10.10.1/12344

